#SPDX-License-Identifier: MIT-0
---
# tasks file for geekoops-prometheus-node_exporter

- name: Ensure prometheus-node_exporter is installed
  ansible.builtin.package:
    name: "golang-github-prometheus-node_exporter"
    state: present

- name: Ensure sysconfig is up-to-date
  ansible.builtin.template:
    src: sysconfig.j2
    dest: '/etc/sysconfig/prometheus-node_exporter'
    owner: root
    group: root
    mode: '0644'

- name: Ensure prometheus-node_exporter is activated
  ansible.builtin.systemd:
    name: 'prometheus-node_exporter'
    enabled: true
    state: started